name: mapas
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  geolocator: ^9.0.2
  geolocator_apple: ^2.2.7
  permission_handler: ^10.3.0
  google_maps_flutter: ^2.3.0
  animate_do: ^3.0.2
  

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
